language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
          packages: ['libedit-dev', 'gcc-8', 'g++-8', 'clang-8', 'llvm-8', 'llvm-8-dev']
      env:
        - CC=gcc-8
        - CXX=g++-8

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
          packages: ['libedit-dev', 'gcc-8', 'g++-8', 'clang-8', 'llvm-8', 'llvm-8-dev']
      env:
        - CC=clang-8
        - CXX=clang++-8

    - os: windows
      env:
        - COOLANG_CMAKE_ARCHITECTURE_FLAG="-A Win32"

    - os: windows
      env:
        - COOLANG_CMAKE_ARCHITECTURE_FLAG="-A x64"

before_script:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install llvm --version=8.0.1 --allow-downgrade; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then wget https://github.com/vovkos/llvm-package-windows/releases/download/llvm-8.0.0/llvm-8.0.0-windows-x86-msvc15-msvcrt.7z -O llvm.7z; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then 7z x llvm.7z -y -o"C:\Program Files (x86)"; fi

script:
  - mkdir build
  - cd build
  - echo $COOLANG_CMAKE_ARCHITECTURE_FLAG
  - cmake .. $COOLANG_CMAKE_ARCHITECTURE_FLAG
  - cmake --build . --config Release
  - ctest --verbose
